feat: print the versions
UziTech/action-setup-atom pull request #152
Opened 2021-01-06 21:13 UTC by aminya

Fixes #149

2021-01-07 05:39 UTC, UziTech requested changes

2021-01-07 05:39 UTC, UziTech commented on src/setup-atom.js
> +let apmPath;
We should have a pass `folder` to `printVersions` and create a function that provides the path instead of using a mutable variable.

2021-03-04 00:27 UTC, aminya commented on src/setup-atom.js
> +let apmPath;
Fixed in https://github.com/UziTech/action-setup-atom/pull/152/commits/2b236d804153bbd8e0612cf99982ada09ca211ea

2021-03-06 02:14 UTC, UziTech commented on src/setup-atom.js
> +async function printVersions(apmPath) {
`apmPath` is always `undefined` on windows. Do we want the `atomPath` to do `atom -v` as well?

2021-03-06 02:55 UTC, UziTech commented on src/setup-atom.js
> +async function printVersions(apmPath) {
Can you add tests to make sure `addToPath` returns a path?

2021-04-10 03:12 UTC, UziTech commented on src/setup-atom.js
> +async function printVersions(apmPath) {
@aminya are you planning on still working on this? I see you created a new action https://github.com/atom-community/action-setup-atom with this merged.

2021-04-10 03:18 UTC, aminya commented on src/setup-atom.js
> +async function printVersions(apmPath) {
`undefined` apmPath is covered by my condition in the print function. I didn't change the path-finding code, so I don't think the tests for it are related to this pull request.

2021-04-10 03:21 UTC, aminya commented on src/setup-atom.js
> +async function printVersions(apmPath) {
> I see you created a new action atom-community/action-setup-atom with this merged.

Yes, I made that fork to support Atom snaps and also printing the versions. It tracks this upstream branch (except for automatic dependency bumps).

2021-04-10 03:48 UTC, UziTech commented on src/setup-atom.js
> +async function printVersions(apmPath) {
it just uses `apm` if `apmPath` is undefined. If that works why not just use `apm` all the time?

2021-04-10 05:11 UTC, closed without merging