feat: support installing Atom using snap
UziTech/action-setup-atom pull request #153
Opened 2021-01-06 21:42 UTC by aminya

Fixes #142

2021-01-06 22:34 UTC, aminya commented
The CodeQL fails. It thinks I am trying to add unsafe shell commands here.

2021-01-06 23:13 UTC, UziTech requested changes

2021-01-06 23:13 UTC, UziTech commented on README.md
> +
Instead of a boolean setting should we make this a string something like `installLocation: "snap"` so we could add other install locations without having a boolean setting for each?

2021-01-06 23:13 UTC, UziTech commented on README.md
> +
We should also figure out a way to use that on windows and mac incase we want to install it from [chocolatey](https://chocolatey.org/packages/Atom/1.53.0) or whatever package managers there are on mac

2021-01-06 23:14 UTC, aminya commented on README.md
> +
That's a good idea.

2021-01-06 23:16 UTC, UziTech commented
I'm thinking this might be a bad idea since it seems like it would be easier to run `sudo snap install ...` instead of using this action if you want to install Atom from a package manager. I don't see what this action offers above running the command for you.

2021-01-06 23:24 UTC, aminya commented
> I'm thinking this might be a bad idea since it seems like it would be easier to run `sudo snap install ...` instead of using this action if you want to install Atom from a package manager. I don't see what this action offers above running the command for you.

The point is to provide a "common interface" that gives an abstraction for installing Atom. We can say that everything can be scripted manually, but the job of these actions is to make them plug-and-play without the need to write a custom script to do so.

2021-01-06 23:29 UTC, UziTech commented
> The point is to provide a "common interface" that gives an abstraction for installing Atom.

Yes but in this case the abstraction would require a lot of effort (maintaining a list of valid Atom install locations and commands) and provide very little benefit. It is actually more typing to use this action and set the settings than to run the command without using this action.

2021-01-06 23:30 UTC, UziTech commented on .github/workflows/test.yml
> +      include:
I think github actions isn't running because `strategy.include` is not valid syntax

2021-01-06 23:36 UTC, aminya commented
> > The point is to provide a "common interface" that gives an abstraction for installing Atom.
> 
> Yes but in this case the abstraction would require a lot of effort (maintaining a list of valid Atom install locations and commands) and provide very little benefit. It is actually more typing to use this action and set the settings than to run the command without using this action.

That is why a common library that allows doing something is very valuable. That's why we write libraries that others can use to achieve their desire. For sure, it requires development effort, but this development effort is done only once. 

For example, in this PR, I have written the snap script only once. Imagine if I want to test Atom snap for 10 packages, now I have to write it 10 times.

Another example is for docker images, someone makes a docker image that can install 6 different Ubuntu versions. This requires maintenance, but that is why it makes this library valuable. 
https://hub.docker.com/_/ubuntu

2021-01-06 23:41 UTC, aminya commented on .github/workflows/test.yml
> +      include:
Fixed in https://github.com/UziTech/action-setup-atom/pull/153/commits/c0dc8dc9f28e152bd0f24353c9436b8ff6dc6c88

2021-01-07 00:40 UTC, UziTech commented
> That is why a common library that allows doing something is very valuable.

Yes but a library that does too much isn't as useful. for instance why don't we also have an option to install vscode or emacs. How about we also run the tests automatically and add run semantic release if tests pass.

We have to stop somewhere. I say we stop at installing official builds.

> Imagine if I want to test Atom snap for 10 packages, now I have to write it 10 times.

If you have 10 packages you will have to run this action 10 times. But in this case it will be easier, or just as easy, to run the command 10 times as it will to run this action 10 times.

2021-01-07 00:46 UTC, UziTech commented
If you really want something like this in this action I say you create and maintain a library with package manager locations and commands and we can import and run it from this action.

2021-01-07 00:56 UTC, UziTech commented
Not to mention, if there is a difference between installing from a package manager and installing from an official build that seems like a problem for the package manager or Atom, not any package. So there should be no reason to test Atom installed from snap or any other package manager.

2021-01-07 01:08 UTC, aminya commented
> If you really want something like this in this action I say you create and maintain a library with package manager locations and commands and we can import and run it from this action.

I can't move the script to a different package because it is hard to test, and that requires duplicating all the dev infrastructure that is available here. 

I prefer forking this repository instead if you prefer not to merge this PR. That is much easier for me.


> Not to mention, if there is a difference between installing from a package manager and installing from an official build that seems like a problem for the package manager or Atom, not any package. So there should be no reason to test Atom installed from snap or any other package manager.

Currently only [snap](https://github.com/snapcrafters/atom/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) seems to be different. [Choco](https://github.com/Thilas/chocolatey-packages/blob/6370b23beb1ba0da2bf1f8e08b35e2ee632f1209/atom.install/tools/chocolateyInstall.ps1#L19) installs directly from the official releases.
Anyways, we need to run the tests so we know the differences. For example, missing glibc is one of the differences we have found out.

Unless we make a PR to Atom itself which detects unofficial installations and throws warnings, we can't stop people from using package managers.

2021-01-07 02:03 UTC, UziTech commented
> we can't stop people from using package managers

You don't have to stop people from using package managers. Just like you don't have to test everyone's fork of Atom. If they don't use an official build it isn't your fault something doesn't work.

And if something is different they, or you, should change it in the package manager not every package.

2021-01-07 02:04 UTC, UziTech commented
Atom might want to test different package managers but no packages should care where Atom is installed from.

2021-01-24 22:25 UTC, UziTech commented
I'm going to close this as this action is meant to be used in Atom packages and they shouldn't have to care about how Atom is installed or change based on how Atom is installed. All packages should have to worry about is which version of Atom and which OS is it installed on.

2021-01-24 22:25 UTC, closed without merging